### ISSUE TITLE
无法屏蔽某些视频的PCDN

### ISSUE THREAD

**Issue by 14185638** [AkagiYui/UserScript#1]

**Comment by AkagiYui** [comment]
请提供视频BV号或其他信息。

**Comment by 14185638** [comment]
不小心按到回车了
![Screenshot_20240818_232335](https://github.com/user-attachments/assets/dc95ce02-1a1f-45da-a80b-63c7c8adba3f)
![Screenshot_20240818_231829](https://github.com/user-attachments/assets/f40ec667-3b8c-4a1d-bea4-827a94439959)

**Comment by 14185638** [comment]
原因找到了，和bilibili-app-recommend插件冲突，一开始确实没想到一个优化网页端推送和排版的插件和屏蔽PCDN冲突

但是，我发现这个插件在开启Hires后就无法屏蔽音频的PCDN了
https://github.com/user-attachments/assets/43802441-05ef-4b20-983a-be62def8a075

**Comment by AkagiYui** [comment]
适配好Hi-Res资源了，请将脚本更新至`0.3.2`版本。

**Comment by 14185638** [comment]
感谢大佬，更新到新版本后问题解决
